# Generated by Django 4.2 on 2024-04-30 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='creacion_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='modificacion_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
