# Generated by Django 4.2 on 2024-04-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0002_alter_profesor_creacion_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='creacion_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='modificacion_registro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
