# Generated by Django 4.2 on 2024-04-30 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordinador', '0003_alter_estudiante_creacion_registro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='curso',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='curso',
            field=models.ManyToManyField(related_name='estudiantes', to='coordinador.curso'),
        ),
    ]
